# Generated by Django 5.2.17 on 2026-09-03 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_staffassignment'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='new_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='old_status',
            field=models.CharField(blank=True, choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DismissedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_alerts', to='events.session')),
            ],
        ),
    ]
